.\" $Id: afterimage-libs.1 281 2011-03-06 18:47:51Z robert $
.\" vim:ft=nroff
.TH AFTERIMAGE-LIBS 1 "September 1st, 2009"
.SH NAME
afterimage-libs - script to get information about the installed version of libAfterImage
.SH SYNOPSIS
.B afterimage-libs
[\-\-external\-only] [\-\-have\-afterbase] [\-\-preferred\-image\-format] 
.SH DESCRIPTION
.PP
\fIafterimage-libs\fP is a tool that is used to configure to determine
the linker flags that should be used to link
programs that use \fIlibAfterImage\fP library.
.PP
When called without any options, 
prints the linker flags that are necessary to link a program using \fIlibAfterImage\fP.
.
.SH OPTIONS
\fIafterimage-libs\fP accepts the following options:
.TP 8
.B  \-\-external\-only
Print the linker flags containing only external (i.e. not coming from afterstep package) libraries needed to link a program 
using \fIlibAfterImage\fP.
.TP 8
.B \-\-have\-afterbase
Print `\fIyes\fP' if \fIlibAfterBase\fP is available.
.TP 8
.B \-\-preferred\-image\-format
Print the image format set as preferred when \fIlibAfterImage\fP was compiled.
.SH COPYRIGHT
\fIlibAfterBase\fP
.nf
        Copyright \(co 1999-2004 Sasha Vasko     <sasha at aftercode.net>
        Copyright \(co 2000,2001 Andrew Ferguson <andrew@owsla.cjb.net>
        Copyright \(co 1999 Ethan Fischer        <allanon@crystaltokyo.com>
        Copyright \(co 1998 Pierre Clerissi      <clerissi@pratique.fr>
.fi
\fIlibAfterImage\fP
.nf
        Copyright \(co 1999-2004 Sasha Vasko <sasha at aftercode.net>
        Copyright \(co 2004 Valeriy Onuchin <Valeri dot Onoutchine at cern dot ch>
        Copyright \(co 2001 Eric Kowalski <eric@beancrock.net>
        Copyright \(co 1999,2001 Ethan Fisher <allanon@crystaltokyo.com>
        Copyright \(co 1999-2001 Free Software Foundation, Inc.
        Copyright \(co 2004 Maxim Nikulin <nikulin at gorodok.net> 
.fi
.PP
This library is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.
.SH AUTHOR
This manual page was written by Robert Luberda <robert@debian.org>,
strongly based on the cppunit-libs man page, which itself
is an almost word-for-word copy of the gtk-libs manpage, written by 
Owen Taylor.  The cppunit-libs man page was modified by E. Sommerlade
<eric@sommerla.de>.
